- type: entity
  id: StellarBaseStationDefensiveOvercharge
  abstract: true
  components:
  - type: StellarOverchargeable
    requiredOvercharge: StellarOverchargeDefensive
  - type: StellarDefensiveOvercharge
