using Content.Client.UserInterface.Controls;
using Content.Stellar.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Stellar.Client.Preferences;

[GenerateTypedNameReferences]
public sealed partial class StellarProfileZoo : FancyWindow
{
    private readonly StellarProfileViewModel _model = new StellarProfileViewModel(new StellarProfile()
    {
        Name = "John Stellar",
        Species = "Human",
        Career = "StellarJobCommandCaptain",
    });

    public StellarProfileZoo()
    {
        RobustXamlLoader.Load(this);
        Left.SetModel(_model);
        Right.SetModel(_model);
    }
}

