using Content.Shared.Humanoid;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Enums;

namespace Content.Stellar.Client.Preferences;

[GenerateTypedNameReferences]
public sealed partial class StellarProfileBasics : Control
{
    private StellarProfileViewModel? _viewModel;

    public StellarProfileBasics()
    {
        RobustXamlLoader.Load(this);

        foreach (var gender in Enum.GetValues<Gender>())
        {
            ProfileGender.AddItem($"xx{gender}", (int)gender);
        }

        ProfileName.OnTextChanged += args => _viewModel!.Name = args.Text;
        ProfileSex.OnItemSelected += args =>
        {
            _viewModel!.Sex = (Sex)args.Id;
        };
        ProfileAge.OnTextChanged += args =>
        {
            if (!int.TryParse(args.Text, out var newAge))
                return;

            _viewModel!.Age = newAge;
        };
        ProfileGender.OnItemSelected += args =>
        {
            _viewModel!.Gender = (Gender)args.Id;
        };
    }

    public void SetModel(StellarProfileViewModel model)
    {
        _viewModel = model;
        UpdateData();
    }

    private void UpdateData()
    {
        if (_viewModel is null)
            return;

        OnNameChanged();
        OnSpeciesChanged();
        OnAgeChanged();
        OnGenderChanged();
        OnSexChanged();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        if (_viewModel is null)
            return;

        _viewModel.NameChanged += OnNameChanged;
        _viewModel.SpeciesChanged += OnSpeciesChanged;
        _viewModel.AgeChanged += OnAgeChanged;
        _viewModel.GenderChanged += OnGenderChanged;
        _viewModel.SexChanged += OnSexChanged;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        if (_viewModel is null)
            return;

        _viewModel.NameChanged -= OnNameChanged;
        _viewModel.SpeciesChanged -= OnSpeciesChanged;
        _viewModel.AgeChanged -= OnAgeChanged;
        _viewModel.GenderChanged -= OnGenderChanged;
        _viewModel.SexChanged -= OnSexChanged;
    }

    private void OnNameChanged()
    {
        ProfileName.Text = _viewModel!.Name;
    }

    private void OnSpeciesChanged()
    {
        ProfileSex.Clear();

        foreach (var sex in _viewModel!.SpeciesSexes)
        {
            ProfileSex.AddItem($"xx{sex}", (int)sex);
        }
        ProfileSex.SelectId((int)_viewModel!.Sex);
    }

    private void OnAgeChanged()
    {
        ProfileAge.Text = _viewModel!.Age.ToString();
    }

    private void OnGenderChanged()
    {
        ProfileGender.SelectId((int)_viewModel!.Gender);
    }

    private void OnSexChanged()
    {
        ProfileSex.SelectId((int)_viewModel!.Sex);
    }
}

